In [42]:
import torch
import numpy as np
import sklearn.metrics as metrics

In [2]:
x = torch.Tensor(3,3)

In [3]:
x

tensor([[4.9489e-15, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 4.1568e-41, 6.7262e-44]])

In [17]:
x[1][2]

tensor(6.3828e+28)

In [4]:
x1 = torch.IntTensor(3,3)
x1

tensor([[721179815,         0,         0],
        [        0,         0,         0],
        [        0,         0,        48]], dtype=torch.int32)

In [5]:
x2 = torch.ShortTensor(3,3)
x2

tensor([[  -28, 11045,     0],
        [    0,     0,     0],
        [    0,     0,     0]], dtype=torch.int16)

In [6]:
x2.dim()

2

In [7]:
x2.size()

torch.Size([3, 3])

In [9]:
x2.type()

'torch.ShortTensor'

In [10]:
x3 = torch.rand(2,3,3)

In [11]:
x3

tensor([[[0.8225, 0.1607, 0.1970],
         [0.0075, 0.9046, 0.4005],
         [0.8245, 0.2683, 0.0833]],

        [[0.3989, 0.9179, 0.5249],
         [0.2884, 0.3505, 0.0434],
         [0.1917, 0.6095, 0.1497]]])

In [12]:
print(x3.dim(), x3.size(), x3.type())

3 torch.Size([2, 3, 3]) torch.FloatTensor


In [13]:
x4 = torch.randint(-10,20,(5,))

In [14]:
x4

tensor([  7,  17,  -3, -10,   6])

In [19]:
x = torch.randint(high=20, size=(3,3))
y = torch.randint(high=30, size=(3,3))

In [20]:
x+y

tensor([[17, 41, 35],
        [29, 23, 16],
        [34, 20, 31]])

In [21]:
torch.add(x,y)

tensor([[17, 41, 35],
        [29, 23, 16],
        [34, 20, 31]])

In [32]:
a_np = np.random.randint(-20,20,(3,3))

In [33]:
a_tr = torch.IntTensor(a_np)

In [38]:
a = torch.randint(high=100, size=(20,))
b = torch.randint(high=100, size=(20,))

In [40]:
def torch_mse(a,b):
    return sum((b-a)**2)/len(a)

In [41]:
torch_mse(a,b)

tensor(2715.5000)

In [43]:
metrics.mean_squared_error(a,b)

2715.5