In [1]:
import pandas as pd
import numpy as np

Создайте два вектора: первый содержит все ответы на вопрос о цене, второй — о качестве. Напечатайте результат на экране (уже в прекоде).


In [3]:
reviews_values = [
    [68,18], [81,19], [81,22], [15,75], [75,15], [17,72],
    [24,75], [21,91], [76, 6], [12,74], [18,83], [20,62],
    [21,82], [21,79], [84,15], [73,16], [88,25], [78,23],
    [32, 81], [77, 35]]

In [4]:
reviews = pd.DataFrame(reviews_values, columns=['Цена', 'Качество'])

In [22]:
price = reviews['Цена'].values
quality = reviews['Качество'].values

In [23]:
print('Цена:', price)

Цена: [68 81 81 15 75 17 24 21 76 12 18 20 21 21 84 73 88 78 32 77]


In [24]:
print('Качество:', quality)

Качество: [18 19 22 75 15 72 75 91  6 74 83 62 82 79 15 16 25 23 81 35]


Определите общее количество покупателей «НосиВипчик». Найдите вектор с оценками клиента с индексом 4 (нумерация индексов начинается с нуля). Напечатайте результат на экране (уже в прекоде).


In [25]:
len(reviews)

20

In [26]:
reviews.loc[4]

Цена        75
Качество    15
Name: 4, dtype: int64

У таблицы есть атрибут values — это двумерный массив. Вызовом функции list() преобразуйте его в список векторов с оценками всех клиентов. Последняя строчка кода выведет результат.


In [27]:
list(reviews.values)

[array([68, 18]),
 array([81, 19]),
 array([81, 22]),
 array([15, 75]),
 array([75, 15]),
 array([17, 72]),
 array([24, 75]),
 array([21, 91]),
 array([76,  6]),
 array([12, 74]),
 array([18, 83]),
 array([20, 62]),
 array([21, 82]),
 array([21, 79]),
 array([84, 15]),
 array([73, 16]),
 array([88, 25]),
 array([78, 23]),
 array([32, 81]),
 array([77, 35])]

In [28]:
%store reviews

Stored 'reviews' (DataFrame)
