# 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
services = ['Минуты', 'СМС', 'Мбайты']
packs_names = ['«За рулём»', '«В метро»']
packs = np.array([
    [20, 5],
    [2, 5],
    [500, 1000]])

clients_packs = np.array([
    [1, 2],
    [2, 3],
    [4, 1],
    [2, 3],
    [5, 0]])

In [3]:
print('Пакеты')
print(pd.DataFrame(clients_packs, columns=packs_names))
print()


Пакеты
   «За рулём»  «В метро»
0           1          2
1           2          3
2           4          1
3           2          3
4           5          0



In [4]:
clients_services = [packs @ client for client in clients_packs]

In [5]:
clients_services

[array([  30,   12, 2500]),
 array([  55,   19, 4000]),
 array([  85,   13, 3000]),
 array([  55,   19, 4000]),
 array([ 100,   10, 2500])]

In [8]:
clients_packs @ packs.T

array([[  30,   12, 2500],
       [  55,   19, 4000],
       [  85,   13, 3000],
       [  55,   19, 4000],
       [ 100,   10, 2500]])

In [10]:
packs @ clients_packs.T

array([[  30,   55,   85,   55,  100],
       [  12,   19,   13,   19,   10],
       [2500, 4000, 3000, 4000, 2500]])

# 2

In [13]:
materials_names = ['Древесная плита', 'Металлическая труба', 'Винты']
venues_names = ['Кофейня', 'Бистро', 'Ресторан']

manufacture = np.array([
    [0.2, 1.2, 8],
    [0.5, 0.8, 6],
    [0.8, 1.6, 8]])

furniture = np.array([
    [12, 0, 3],
    [40, 2, 10],
    [60, 6, 18]])



In [14]:
venues_materials = furniture @ manufacture

print('По заведениям')
print(pd.DataFrame(venues_materials, index=venues_names, columns=materials_names))
print()

По заведениям
          Древесная плита  Металлическая труба  Винты
Кофейня               4.8                 19.2  120.0
Бистро               17.0                 65.6  412.0
Ресторан             29.4                105.6  660.0



In [16]:
venues = np.array([18, 12, 7])

total_materials = venues_materials.T @ venues

print('Всего')
print(pd.DataFrame([total_materials], index=[''], columns=materials_names))


Всего
  Древесная плита  Металлическая труба    Винты
            496.2               1872.0  11724.0


In [24]:
n = np.random.normal(0, 1, size=(3,3))

In [25]:
n_inv = np.linalg.inv(n)

In [26]:
n @ n_inv

array([[ 1.00000000e+00, -2.77555756e-17, -5.20417043e-18],
       [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])